hilti: uncaught exception, InternalError with argument My personal internal error. (from internal-error.hlt:12)
