# $Id$
#
# @TEST-EXEC:  hilti-build %INPUT -o a.out 
# @TEST-EXEC:  ./a.out >output 2>&1
# @TEST-EXEC:  test-diff output
# 
# These are all supposed to throw exceptions.

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    
    l = new list<int32>
    i = list.pop_front l
}     

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    
    l = new list<int32>
    i = list.pop_back l
}     

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    
    l = new list<int32>
    i = list.front l
}     

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    
    l = new list<int32>
    i = list.back l
}     

