>>> call foo 42
wrong-calls.hlt:13: error, operand 2 must be of type tuple but is int<64>

wrong-calls.hlt: 1 error found during validating
